const fireAudio=document.querySelector('#fire-audio');const musicButton=document.querySelector('#music-button');const volumeControl=document.querySelector('#volume');fireAudio.volume=.35;volumeControl.addEventListener('input',()=>{fireAudio.volume=Number(volumeControl.value)/100});musicButton.addEventListener('click',event=>{event.stopImmediatePropagation();if(fireAudio.paused){fireAudio.play();musicButton.textContent='♨ 壁爐回聲施放中';}else{fireAudio.pause();musicButton.textContent='♨ 召喚壁爐回聲';}},true);
document.querySelector('#enter-site').addEventListener('click',()=>{document.querySelector('#prelude').classList.add('leave');document.querySelector('#site-main').classList.add('entered');document.body.classList.add('site-entered');fireAudio.volume=.35;fireAudio.play().catch(()=>{});document.querySelector('#music-button').textContent='♨ 壁爐回聲施放中';});
const floatingPhrases=['有些故事，只在火光裡說得出口。','你看到的最後一句，會成為下一個人的起點。','今晚留下的，不一定明天還找得到。','請把一句話交給陌生人，讓他替你帶走。','午夜以前，這個故事還屬於我們。'];let floatingIndex=0;const floatingPhrase=document.querySelector('#floating-phrase');setInterval(()=>{floatingPhrase.classList.add('fade-out');setTimeout(()=>{floatingIndex=(floatingIndex+1)%floatingPhrases.length;floatingPhrase.textContent=floatingPhrases[floatingIndex];floatingPhrase.classList.remove('fade-out');},650);},4300);
const screens=[...document.querySelectorAll('[data-screen]')],dots=[...document.querySelectorAll('.page-dot')];let currentScreen=0;function showScreen(index){currentScreen=(index+screens.length)%screens.length;screens.forEach((screen,i)=>screen.classList.toggle('active-page',i===currentScreen));dots.forEach((dot,i)=>dot.classList.toggle('active',i===currentScreen));document.querySelector('#prev-page').disabled=currentScreen===0;document.querySelector('#next-page').disabled=currentScreen===screens.length-1;}document.querySelector('#prev-page').addEventListener('click',()=>showScreen(currentScreen-1));document.querySelector('#next-page').addEventListener('click',()=>showScreen(currentScreen+1));dots.forEach(dot=>dot.addEventListener('click',()=>showScreen(Number(dot.dataset.page))));showScreen(0);
const form=document.querySelector('#relay-form'), entry=document.querySelector('#entry'), chars=document.querySelector('#chars'), success=document.querySelector('#success'), progress=document.querySelector('#progress'), countdown=document.querySelector('#countdown');
const bannedWords=['幹','媽的','他媽','操','靠北','靠夭','雞巴','王八蛋','智障','白痴','fuck','shit','bitch','asshole'];
function hasBannedWords(text){const normalized=text.toLowerCase().replace(/[\s\u200b]/g,'');return bannedWords.some(word=>normalized.includes(word));}
entry.addEventListener('input',()=>{chars.textContent=`${entry.value.length} / 100`;document.querySelector('#content-warning').textContent='';});
form.addEventListener('submit',e=>{e.preventDefault();if(!entry.value.trim())return;if(hasBannedWords(entry.value)){document.querySelector('#content-warning').textContent='這段文字包含不適合公開的用語，請換一種方式表達。';return;}form.style.display='none';success.style.display='block';document.querySelector('#ticket-button-home').disabled=false;progress.textContent='74';document.querySelector('#spots').textContent='還有 26 個位置';document.querySelector('#last-line').textContent=entry.value.trim();document.querySelector('#status').textContent='你已留下句子';});
let demoMode=false;function secondsToMidnight(){const now=new Date(),end=new Date(now);end.setHours(24,0,0,0);return Math.max(0,Math.floor((end-now)/1000));}function renderCountdown(){if(demoMode)return;const remaining=secondsToMidnight(),h=String(Math.floor(remaining/3600)).padStart(2,'0'),m=String(Math.floor(remaining%3600/60)).padStart(2,'0'),s=String(remaining%60).padStart(2,'0');countdown.textContent=`${h}:${m}:${s}`;}renderCountdown();setInterval(renderCountdown,1000);
const demoLines=['我一直以為，告別應該發生在我們都準備好的時候。','直到那天，我才發現，有些人甚至不會通知你，就從你的生活裡消失。','我把他的名字從通訊錄刪掉，卻還是記得那串號碼。','那串號碼像一扇關不起來的門，夜裡總有風從裡面吹出來。','有人說，遺忘是一種溫柔；可我覺得它比較像房間裡慢慢熄滅的燈。','燈熄滅後，我看見桌上多了一封沒有寄件人的信。','信封很輕，裡面卻裝著整個下午的雨聲。','我沒有立刻拆開，先把它放在火爐旁邊取暖。','紙邊開始捲起來時，字跡忽然自己換了位置。','它寫著：有些話不是要被讀完，而是要有人接下去。','於是我拿起筆，在最後一行留下了一個陌生人的名字。','窗外的雪停了，壁爐裡只剩下很小、很小的紅光。','那道紅光提醒我，故事還沒有結束，只是暫時換了一個人呼吸。','我想起今天第一個留下句子的人，他大概也正在某個房間裡等著。','等一個答案，或等下一個人替他寫下去。','謝謝你曾經在我的故事裡出現。就到這裡吧，晚安。'];
const storyView=document.querySelector('#story-view'), storyLines=document.querySelector('#story-lines');
document.querySelector('#unlock-demo').addEventListener('click',()=>{storyLines.innerHTML=demoLines.map((line,i)=>`<div class="story-line ${i===7?'my-line':''}"><span>匿名段落 ${String(i+1).padStart(2,'0')}${i===7?' · 你的句子':''}</span>${line}</div>`).join('');storyView.classList.add('open');storyView.setAttribute('aria-hidden','false');storyView.scrollIntoView({behavior:'smooth',block:'start'});});
document.querySelector('#close-story').addEventListener('click',()=>{storyView.classList.remove('open');storyView.setAttribute('aria-hidden','true');});
document.querySelector('#burn-demo').addEventListener('click',()=>{demoMode=!demoMode;document.body.classList.toggle('burning');document.querySelector('#burn-stage').classList.toggle('open',demoMode);document.querySelector('#burn-stage').setAttribute('aria-hidden',String(!demoMode));document.querySelector('#status').textContent=demoMode?'即將銷毀':'接龍進行中';if(demoMode)document.querySelector('#countdown').textContent='00:04:59';else renderCountdown();});
document.querySelector('#close-burn').addEventListener('click',()=>{demoMode=false;document.body.classList.remove('burning');document.querySelector('#burn-stage').classList.remove('open');document.querySelector('#burn-stage').setAttribute('aria-hidden','true');document.querySelector('#status').textContent='接龍進行中';renderCountdown();});
document.querySelector('#ticket-button-home').addEventListener('click',()=>{document.querySelector('#ticket-result-home').textContent='✦ 你是今晚第 74 位注入靈魂的陌生人 · 數位火柴已點燃';});
document.querySelectorAll('[data-vote]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-vote]').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');document.querySelector('#vote-result').textContent=`你投給了「${btn.dataset.vote}」`; }));
let audioCtx,master,noiseSource;document.querySelector('#music-button').addEventListener('click',()=>{const button=document.querySelector('#music-button');if(!audioCtx){audioCtx=new AudioContext();master=audioCtx.createGain();master.gain.value=.07;master.connect(audioCtx.destination);const bass=audioCtx.createOscillator();bass.type='sine';bass.frequency.value=58;const bassGain=audioCtx.createGain();bassGain.gain.value=.1;bass.connect(bassGain).connect(master);bass.start();const lfo=audioCtx.createOscillator(),lfoGain=audioCtx.createGain();lfo.frequency.value=.045;lfoGain.gain.value=10;lfo.connect(lfoGain).connect(bass.frequency);lfo.start();const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*2,audioCtx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.18;noiseSource=audioCtx.createBufferSource();noiseSource.buffer=buffer;noiseSource.loop=true;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=560;noiseSource.connect(filter).connect(master);noiseSource.start();let crackleTimer=setInterval(()=>{if(audioCtx.state!=='running')return;const pop=audioCtx.createBufferSource(),popBuffer=audioCtx.createBuffer(1,audioCtx.sampleRate*(.08+Math.random()*.18),audioCtx.sampleRate),popData=popBuffer.getChannelData(0);for(let i=0;i<popData.length;i++)popData[i]=(Math.random()*2-1)*Math.pow(1-i/popData.length,2.5);pop.buffer=popBuffer;const popGain=audioCtx.createGain();popGain.gain.value=.08+Math.random()*.12;const popFilter=audioCtx.createBiquadFilter();popFilter.type='bandpass';popFilter.frequency.value=500+Math.random()*900;pop.connect(popFilter).connect(popGain).connect(master);pop.start();},900+Math.random()*1800);button.textContent='♫ 露營火堆聲播放中';}else if(audioCtx.state==='running'){audioCtx.suspend();button.textContent='♫ 播放露營火堆聲';}else{audioCtx.resume();button.textContent='♫ 露營火堆聲播放中';}});
